[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-module-docstring",
    "missing-class-docstring",
    "invalid-name"
]

[tool.black]
line-length = 80
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
