# pylint: disable=line-too-long
crop_info = {
    "rice": {
        "Soil": "Clayey or loamy soil with good water retention",
        "Planting Season": "July and August or January and June",
        "Region": "Lowland areas with abundant water like river valleys, coastal plains, and wetlands",
        "Land Preparation": "Puddling and leveling the field",
        "Soil Fertility Management": "Application of organic manure and fertilizers",
        "Weed Management": "Hand weeding, mechanical weeding, or use of herbicides",
        "Sunlight": "6-8 hours of sunlight per day",
        "Spacing": "15-20 cm between plants and 20-25 cm between rows",
        "Harvesting Time": "120-150 days after planting, when the grains are firm and golden",
    },
    "maize": {
        "Soil": "Well-drained, fertile loamy or sand loam soil",
        "Planting Season": "During the start of the rainy season",
        "Region": "Plains, valleys, highlands",
        "Land Preparation": "Plowing and harrowing",
        "Soil Fertility Management": "Application of NPK fertilizers",
        "Weed Management": "Manual or chemical weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "25-30 cm between plants and 60-75 cm between rows",
        "Harvesting Time": "75-120 days after planting, when the kernels are full and hard",
    },
    "chickpea": {
        "Soil": "Well-drained loamy or sandy soil",
        "Planting Season": "October to February",
        "Region": "Drylands, plains, slopes",
        "Land Preparation": "Plowing and leveling",
        "Soil Fertility Management": "Application of phosphorus-rich fertilizers",
        "Weed Management": "Manual weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "10-15 cm between plants and 30 cm between rows",
        "Harvesting Time": "90-120 days after planting, when the pods are dry and brown.",
    },
    "kidneybeans": {
        "Soil": "Well-drained loamy or sandy soil",
        "Planting Season": "June to September",
        "Region": "Plains, valleys, slopes",
        "Land Preparation": "Plowing and harrowing",
        "Soil Fertility Management": "Application of organic manure",
        "Weed Management": "Manual weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "30-45 cm between plants",
        "Harvesting Time": "90-120 days after planting",
    },
    "pigeonpeas": {
        "Soil": "Well-drained loamy or clayey soil",
        "Planting Season": "Kharif (June to September)",
        "Region": "Plains, drylands, slopes",
        "Land Preparation": "Plowing and leveling",
        "Soil Fertility Management": "Application of organic manure and phosphorus-rich fertilizers",
        "Weed Management": "Manual weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "60-75 cm between plants",
        "Harvesting Time": "150-180 days after planting",
    },
    "mothbeans": {
        "Soil": "Well-drained sandy or loamy soil",
        "Planting Season": "Kharif (June to September)",
        "Region": "Drylands, plains, slopes",
        "Land Preparation": "Plowing and harrowing",
        "Soil Fertility Management": "Application of organic manure",
        "Weed Management": "Manual weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "30-45 cm between plants",
        "Harvesting Time": "60-90 days after planting",
    },
    "mungbean": {
        "Soil": "Well-drained loamy or sandy soil",
        "Planting Season": "Kharif and Rabi",
        "Region": "Plains, drylands, valleys",
        "Land Preparation": "Plowing and leveling",
        "Soil Fertility Management": "Application of phosphorus-rich fertilizers",
        "Weed Management": "Manual weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "30-45 cm between plants",
        "Harvesting Time": "60-75 days after planting",
    },
    "blackgram": {
        "Soil": "Well-drained loamy or sandy soil",
        "Planting Season": "Kharif (June to September)",
        "Region": "Plains, drylands, valleys",
        "Land Preparation": "Plowing and leveling",
        "Soil Fertility Management": "Application of organic manure and phosphorus-rich fertilizers",
        "Weed Management": "Manual weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "30-45 cm between plants",
        "Harvesting Time": "70-90 days after planting",
    },
    "lentil": {
        "Soil": "Well-drained loamy or clayey soil",
        "Planting Season": "Rabi (October to February)",
        "Region": "Plains, valleys, highlands",
        "Land Preparation": "Plowing and leveling",
        "Soil Fertility Management": "Application of phosphorus-rich fertilizers",
        "Weed Management": "Manual weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "15-20 cm between plants",
        "Harvesting Time": "110-130 days after planting",
    },
    "pomegranate": {
        "Soil": "Well-drained loamy or sandy soil",
        "Planting Season": "Spring and summer",
        "Region": "Plains, valleys, drylands",
        "Land Preparation": "Plowing and leveling",
        "Soil Fertility Management": "Application of organic manure and balanced fertilizers",
        "Weed Management": "Manual or chemical weeding",
        "Sunlight": "Full sun, 6-8 hours of sunlight per day",
        "Spacing": "4-5 meters between plants",
        "Harvesting Time": "2-3 years for tree maturity; 150-180 days after flowering for fruit harvesting",
    },
    "banana": {
        "Soil": "Deep, well-drained loamy soil",
        "Planting Season": "Throughout the year, best during the rainy season",
        "Region": "Coastal regions, lowlands, and mid-altitudes",
        "Land Preparation": "Clear land and dig pits filled with compost or manure",
        "Soil Fertility Management": "Regular application of organic manure and balanced fertilizers",
        "Weed Management": "Regular weeding or mulching",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "2-3 meters between plants",
        "Harvesting Time": "9-12 months after planting",
    },
    "mango": {
        "Soil": "Well-drained, deep sandy loam soil",
        "Planting Season": "Rainy season (April-June)",
        "Region": "Lowlands, mid-altitudes, and dry regions",
        "Land Preparation": "Dig large pits and mix soil with organic manure",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers annually",
        "Weed Management": "Regular weeding and mulching",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "8-10 meters between plants",
        "Harvesting Time": "4-5 years after planting for mature trees",
    },
    "grapes": {
        "Soil": "Well-drained sandy loam soil with good organic matter",
        "Planting Season": "Late winter or early spring",
        "Region": "Highlands and dry regions",
        "Land Preparation": "Clear land, plow, and add organic manure",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers",
        "Weed Management": "Mulching or manual weeding",
        "Sunlight": "Requires full sunlight, 6-8 hours per day",
        "Spacing": "1.5-3 meters between vines",
        "Harvesting Time": "2-3 years after planting",
    },
    "watermelon": {
        "Soil": "Well-drained sandy loam soil",
        "Planting Season": "During warm season (March-June)",
        "Region": "Lowlands and plains",
        "Land Preparation": "Clear land, plow, and create raised beds",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers",
        "Weed Management": "Regular weeding and mulching",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "1-2 meters between plants",
        "Harvesting Time": "80-100 days after planting",
    },
    "muskmelon": {
        "Soil": "Well-drained sandy loam soil",
        "Planting Season": "During warm season (March-June)",
        "Region": "Lowlands and plains",
        "Land Preparation": "Clear land, plow, and create raised beds",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers",
        "Weed Management": "Regular weeding and mulching",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "1-2 meters between plants",
        "Harvesting Time": "70-90 days after planting",
    },
    "apple": {
        "Soil": "Well-drained loamy soil",
        "Planting Season": "During the dormant season (June-July)",
        "Region": "Highlands and cool regions",
        "Land Preparation": "Clear land, dig large pits, and mix soil with organic manure",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers annually",
        "Weed Management": "Regular weeding and mulching",
        "Sunlight": "Requires full sunlight, 6-8 hours per day",
        "Spacing": "4-6 meters between plants",
        "Harvesting Time": "3-4 years after planting for mature trees",
    },
    "orange": {
        "Soil": "Well-drained sandy loam soil",
        "Planting Season": "Rainy season (April-June)",
        "Region": "Lowlands, mid-altitudes, and dry regions",
        "Land Preparation": "Dig large pits and mix soil with organic manure",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers annually",
        "Weed Management": "Regular weeding and mulching",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "6-8 meters between plants",
        "Harvesting Time": "3-5 years after planting for mature trees",
    },
    "papaya": {
        "Soil": "Well-drained loamy soil",
        "Planting Season": "Throughout the year, best during the rainy season",
        "Region": "Lowlands and mid-altitudes",
        "Land Preparation": "Clear land, dig pits, and mix soil with organic manure",
        "Soil Fertility Management": "Regular application of organic manure and fertilizers",
        "Weed Management": "Regular weeding or mulching",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "2-3 meters between plants",
        "Harvesting Time": "9-12 months after planting",
    },
    "coconut": {
        "Soil": "Well-drained sandy or loamy soil",
        "Planting Season": "Rainy season (April-June)",
        "Region": "Coastal regions and lowlands",
        "Land Preparation": "Clear land, dig large pits, and mix soil with organic manure",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers annually",
        "Weed Management": "Regular weeding and mulching",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "8-10 meters between plants",
        "Harvesting Time": "5-7 years after planting for mature trees",
    },
    "cotton": {
        "Soil": "Well-drained loamy or sandy soil",
        "Planting Season": "Early rainy season (March-May)",
        "Region": "Lowlands and dry regions",
        "Land Preparation": "Clear land, plow, and create ridges",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers",
        "Weed Management": "Regular weeding or chemical control",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "1-1.5 meters between plants",
        "Harvesting Time": "5-6 months after planting",
    },
    "jute": {
        "Soil": "Loamy or clayey soil with good drainage",
        "Planting Season": "Early rainy season (March-April)",
        "Region": "Lowlands and river valleys",
        "Land Preparation": "Clear land, plow, and level the field",
        "Soil Fertility Management": "Apply organic manure and balanced fertilizers",
        "Weed Management": "Regular weeding",
        "Sunlight": "Requires full sunlight, 8-10 hours per day",
        "Spacing": "10-15 cm between plants",
        "Harvesting Time": "100-120 days after planting",
    },
    "coffee": {
        "Soil": "Well-drained, fertile loamy soil",
        "Planting Season": "Rainy season (April-June)",
        "Region": "Highlands and slopes",
        "Land Preparation": "Clear land, dig pits, and mix soil with organic manure",
        "Soil Fertility Management": "Regular application of organic manure and fertilizers",
        "Weed Management": "Regular weeding or mulching",
        "Sunlight": "Requires partial sunlight, 4-6 hours per day",
        "Spacing": "2-3 meters between plants",
        "Harvesting Time": "3-4 years after planting for mature trees",
    },
}
