name: Continuous Integration
on:
  push:
    branches:
      - 'main'
    paths:
      - 'streamlit/**'
      - 'model/**'

jobs:
  test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - name: Cache pip dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pipenv
      #     key: pipenv-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
      #     restore-keys: |
      #       pipenv-${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd streamlit
          python -m pip install --upgrade pip
          pip install pipenv && pipenv install --dev

      - name: Running linting
        run: |
          cd streamlit
          pipenv run pylint --recursive=y .
          pipenv run black .
          # pipenv run isort --ls .
