name: Continuous Intergration
on:
  push:
    branches:
      - 'main'
    paths:
      - 'streamlit/**'
      - 'model/**'

jobs:
  test:
    name: Continuous Intergration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd streamlit
          python -m pip install --upgrade pip
          pip install pipenv && pipenv install --dev

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pipenv
          key: pipenv-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            pipenv-${{ runner.os }}-pip-

      - name: Running linting
        run: |
          cd streamlit
          pipenv run pylint --recursive=y .

      - name: Run formatting
        run: |
          cd streamlit
          pipenv run black .
          pipenv run isort .
